### ISSUE TITLE
프로젝트 피드백 - 작성자: 오창영 튜터

### ISSUE THREAD

**Issue by ghost** [HyunseoY/GOE_TODO#1]
- 전반적으로 깔끔하고 군더더기 없이 잘 구현하셨습니다.
- main 브랜치에서 바로 작업하신 것으로 보입니다. 팀프로젝트를 위해 개인프로젝트에서도 브랜치를 생성하시고 PR 사용해보는 걸 추천드립니다.
- README에 해당 프로젝트 설명, 특성을 추가하시면 좋을 것 같습니다.
- focus, hover 등 사용자 동작에 따른 인터랙션 잘 적용해주셨습니다.
- 배포까지 하셨네요 좋습니다!

추가적으로 아래에 파일들에 대한 리뷰 남기겠습니다.

**Comment by ghost** [comment]
## Detail.jsx

https://github.com/HyunseoY/GOE_TODO/blob/42894253f26e63a92fb770144c2aba1bc60c9912/src/pages/Detail.jsx#L11-L13

== 보단 ===로 비교해주세요.

**Comment by ghost** [comment]
## module/todo.js

https://github.com/HyunseoY/GOE_TODO/blob/42894253f26e63a92fb770144c2aba1bc60c9912/src/redux/modules/todos.js#L42-L52

filter는 조건 만족하는 요소들을 새로운 배열로 반환하는 메서드입니다. 내부에서 값을 변경하는 용도로 쓰기엔 적합하지 않습니다.

**Comment by HyunseoY** [comment]
감사합니다!
